---
- name: Build and Publish Docker Image
  hosts: web1
  gather_facts: false

  tasks:
    - name: Build Docker Image
      command: "docker build -t msekandi/abctechnologies-latest-with-ansible -f /tmp/ABC-Technologies/Dockerfile /root/jenkins/workspace/ABC-Technologies"

    - name: Log in to Docker Hub
      shell: "docker login -u {{ docker_username }} -p {{ docker_password }}"
      register: docker_login_result
      ignore_errors: yes

    - name: Push to Docker Hub
      shell: "docker push msekandi/abctechnologies-latest-with-ansible"
      environment:
        DOCKER_CLI_AGGREGATE: "1"
      when: docker_login_result is success
