---
- name: Build and Publish Docker Image
  hosts: web1
  gather_facts: false

  tasks:
    - name: Clone Git repository
      git:
        repo: https://github.com/msekandi/ABC-Technologies.git
        dest: /tmp/ABC-Technologies

    - name: Build Docker Image
      command: "docker build -t msekandi/abctechnologies-latest -f /tmp/ABC-Technologies/Dockerfile /tmp/ABC-Technologies"
      
    - name: Push to Docker Hub
      command: >
        withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
    script {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            sh 'docker push msekandi/abctechnologies-latest'
        }
    }
}

      environment:
        DOCKER_CLI_AGGREGATE: "1"
