---
- name: Build and Publish Docker Image
  hosts: kubernetes_cluster
  gather_facts: false

  tasks:
    - name: Build Docker Image
      command: "docker build -t msekandi/abctechnologies-latest -f /tmp/ABC-Technologies/Dockerfile /tmp/ABC-Technologies"

    - name: Push to Docker Hub
      command: >
        docker login -u "{{ docker_username }}" -p "{{ docker_password }}" &&
        docker push msekandi/abctechnologies-latest
      environment:
        DOCKER_CLI_AGGREGATE: "1"
