---
- name: Clone Git repository
  hosts: web1
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa

  tasks:
    - name: Clone Git repository
      git:
        repo: https://github.com/msekandi/ABC-Technologies.git
        dest: /tmp/ABC-Technologies
      become: true
