---
- name: Deploy Docker image to Kubernetes
  hosts: web1
  tasks:
    - name: Deploy Kubernetes Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-technologies-deployment
            namespace: abc-technologies
            labels:
              app: abc-technologies
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: abc-technologies
            template:
              metadata:
                labels:
                  app: abc-technologies
              spec:
                containers:
                  - name: abc-technologies-container
                    image: msekandi/abctechnologies-latest-with-ansible
                    ports:
                      - containerPort: 8085
                    resources:  # Add this resources section
                      limits:
                        memory: "256Mi"  # Adjust memory limit as needed
                        cpu: "500m"       # Adjust CPU limit as needed
                      requests:
                        memory: "128Mi"  # Adjust memory request as needed
                        cpu: "250m"       # Adjust CPU request as needed
