---
- name: Deploy Docker image to Kubernetes
  hosts: web1
  tasks:
    - name: Deploy Kubernetes Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-technologies-deployment
            namespace: abc-technologies
            labels:
              app: abc-technologies
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: abc-technologies
            template:
              metadata:
                labels:
                  app: abc-technologies
              spec:
                containers:
                  - name: abc-technologies-container
                    image: msekandi/abctechnologies-latest
                    ports:
                      - containerPort: 8085
                    resources:
                      limits:
                        cpu: "1"
                        memory: "512Mi"
                      requests:
                        cpu: "500m"
                        memory: "256Mi"
