---
- name: Deploy Docker image to Kubernetes
  hosts: web1
  tasks:
    - name: Deploy Kubernetes Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: abc-technologies-deployment
            namespace: abc-technologies
            labels:
              app: abc-technologies
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: abc-technologies
            template:
              metadata:
                labels:
                  app: abc-technologies
              spec:
                containers:
                  - name: abc-technologies-container
                    image: msekandi/abctechnologies-latest
                    ports:
                      - containerPort: 8085
                    resources:
                      limits:
                        cpu: "1" 
                        memory: "512Mi" 
                      requests:
                        cpu: "500m" 
                        memory: "256Mi" 

apiVersion: v1
kind: Service
metadata:
  name: abc-technologies-service
  namespace: abc-technologies
spec:
  selector:
    app: abc-technologies
  ports:
    - protocol: TCP
      port: 8080  # Port exposed by your application container
      targetPort: 8085  # Port your application is listening on
      nodePort: 30000  # Choose an available port within the range 30000-32767
  type: NodePort
